### ISSUE TITLE
Can you rename this to dwiprep / make a new repo?

### ISSUE THREAD

**Issue by kochalka** [StanfordCosyne/hardi_prep#1]
DTI is one specific and outdated method for analyzing diffusion MRI data...

**Comment by madeleinesnyder** [comment]
what's a better name?

**Comment by madeleinesnyder** [comment]
I'm trying to install a static version of mrtrix but there doesn't appear
to be one-- did you just clone the git repo or is there a place I can get
an archived tar version to install with curl in the dockerfile?
